const catalogCategorySubcategoryQueries = [
  // {
  //   catalog: 'men',
  //   category: 'tops',
  //   subcategory: 't-shirts',
  //   query: 'men t-shirts',
  // },
  // {
  //   catalog: 'men',
  //   category: 'tops',
  //   subcategory: 'tank-tops',
  //   query: 'men tank tops',
  // },
  // {
  //   catalog: 'men',
  //   category: 'tops',
  //   subcategory: 'long-sleeve-shirts',
  //   query: 'men long sleeve shirts',
  // },
  // {
  //   catalog: 'men',
  //   category: 'tops',
  //   subcategory: 'compression-tops',
  //   query: 'men compression tops',
  // },
  // {
  //   catalog: 'men',
  //   category: 'bottoms',
  //   subcategory: 'shorts',
  //   query: 'men shorts',
  // },
  // {
  //   catalog: 'men',
  //   category: 'bottoms',
  //   subcategory: 'joggers',
  //   query: 'men joggers',
  // },
  // {
  //   catalog: 'men',
  //   category: 'bottoms',
  //   subcategory: 'sweatpants',
  //   query: 'men sweatpants',
  // },
  // {
  //   catalog: 'men',
  //   category: 'outerwear',
  //   subcategory: 'hoodies-sweatshirts',
  //   query: 'men hoodies',
  // },
  // {
  //   catalog: 'men',
  //   category: 'outerwear',
  //   subcategory: 'jackets',
  //   query: 'men jackets',
  // },
  // {
  //   catalog: 'men',
  //   category: 'outerwear',
  //   subcategory: 'windbreakers',
  //   query: 'men windbreakers',
  // },
  {
    catalog: 'men',
    category: 'footwear',
    subcategory: 'running-shoes',
    query: 'men running shoes',
  },
  {
    catalog: 'men',
    category: 'footwear',
    subcategory: 'training-shoes',
    query: 'men training shoes',
  },
  {
    catalog: 'men',
    category: 'footwear',
    subcategory: 'casual-sneakers',
    query: 'men casual sneakers',
  },
  {
    catalog: 'men',
    category: 'accessories',
    subcategory: 'caps',
    query: 'men caps',
  },
  {
    catalog: 'men',
    category: 'accessories',
    subcategory: 'socks',
    query: 'men socks',
  },
  {
    catalog: 'men',
    category: 'accessories',
    subcategory: 'gym-bags',
    query: 'men gym bags',
  },
  {
    catalog: 'men',
    category: 'accessories',
    subcategory: 'gloves',
    query: 'men gloves',
  },

  {
    catalog: 'women',
    category: 'tops',
    subcategory: 'sports-bras',
    query: 'women sports bras',
  },
  {
    catalog: 'women',
    category: 'tops',
    subcategory: 'crop-tops',
    query: 'women crop tops',
  },
  {
    catalog: 'women',
    category: 'tops',
    subcategory: 'tanks-tees',
    query: 'women tanks tees',
  },
  {
    catalog: 'women',
    category: 'tops',
    subcategory: 'long-sleeve-shirts',
    query: 'women long sleeve shirts',
  },
  {
    catalog: 'women',
    category: 'bottoms',
    subcategory: 'leggings',
    query: 'women leggings',
  },
  {
    catalog: 'women',
    category: 'bottoms',
    subcategory: 'shorts',
    query: 'women shorts',
  },
  {
    catalog: 'women',
    category: 'bottoms',
    subcategory: 'joggers',
    query: 'women joggers',
  },
  {
    catalog: 'women',
    category: 'outerwear',
    subcategory: 'hoodies',
    query: 'women hoodies',
  },
  {
    catalog: 'women',
    category: 'outerwear',
    subcategory: 'jackets',
    query: 'women jackets',
  },
  {
    catalog: 'women',
    category: 'outerwear',
    subcategory: 'sweatshirts',
    query: 'women sweatshirts',
  },
  {
    catalog: 'women',
    category: 'footwear',
    subcategory: 'running-shoes',
    query: 'women running shoes',
  },
  {
    catalog: 'women',
    category: 'footwear',
    subcategory: 'training-shoes',
    query: 'women training shoes',
  },
  {
    catalog: 'women',
    category: 'footwear',
    subcategory: 'lifestyle-sneakers',
    query: 'women sneakers',
  },
  {
    catalog: 'women',
    category: 'accessories',
    subcategory: 'hairbands-scrunchies',
    query: 'hairbands scrunchies',
  },
  {
    catalog: 'women',
    category: 'accessories',
    subcategory: 'water-bottles',
    query: 'water bottles',
  },
  {
    catalog: 'women',
    category: 'accessories',
    subcategory: 'gym-bags',
    query: 'women gym bags',
  },
  {
    catalog: 'women',
    category: 'accessories',
    subcategory: 'socks',
    query: 'women socks',
  },
  {
    catalog: 'women',
    category: 'collections',
    subcategory: 'matching-sets',
    query: 'matching gym sets women',
  },
  {
    catalog: 'women',
    category: 'collections',
    subcategory: 'maternity-activewear',
    query: 'maternity activewear',
  },

  {
    catalog: 'kids',
    category: 'all-clothings',
    subcategory: 'activewear-sets',
    query: 'kids activewear sets',
  },
  {
    catalog: 'kids',
    category: 'all-clothings',
    subcategory: 'sports-specific-apparel',
    query: 'kids sportswear',
  },
  {
    catalog: 'kids',
    category: 'all-clothings',
    subcategory: 'athleisure-lifestyle-gymwear',
    query: 'kids lifestyle gymwear',
  },
  {
    catalog: 'kids',
    category: 'all-clothings',
    subcategory: 'swimwear-rash-guards',
    query: 'kids swimwear',
  },
  {
    catalog: 'kids',
    category: 'all-clothings',
    subcategory: 'outerwear-layering-essentials',
    query: 'kids outerwear',
  },
  {
    catalog: 'kids',
    category: 'footwears',
    subcategory: 'all-terrain-trainers',
    query: 'kids terrain shoes',
  },
  {
    catalog: 'kids',
    category: 'footwears',
    subcategory: 'procourt-kicks',
    query: 'kids court shoes',
  },
  {
    catalog: 'kids',
    category: 'footwears',
    subcategory: 'easygo-sneakers',
    query: 'kids sneakers',
  },
  {
    catalog: 'kids',
    category: 'footwears',
    subcategory: 'cloudstep-slides',
    query: 'kids slides',
  },
  {
    catalog: 'kids',
    category: 'accessories',
    subcategory: 'backpacks',
    query: 'kids backpacks',
  },
  {
    catalog: 'kids',
    category: 'accessories',
    subcategory: 'cap-headbands',
    query: 'kids headbands',
  },
  {
    catalog: 'kids',
    category: 'accessories',
    subcategory: 'water-bottles',
    query: 'kids water bottles',
  },
  {
    catalog: 'kids',
    category: 'accessories',
    subcategory: 'socks-compression-wear',
    query: 'kids socks compression wear',
  },
  {
    catalog: 'kids',
    category: 'accessories',
    subcategory: 'wristbands-sweatbands',
    query: 'kids wristbands',
  },
  {
    catalog: 'kids',
    category: 'accessories',
    subcategory: 'gloves-protective-gear',
    query: 'kids gloves',
  },
];
